-- Insert all Bangladesh divisions, districts, and upazilas into delivery_zones
INSERT INTO delivery_zones (division, zilla, upazilla, charge, is_active) VALUES
('Dhaka', 'Dhaka', 'Dhamrai', 0, true),
('Dhaka', 'Dhaka', 'Dohar', 0, true),
('Dhaka', 'Dhaka', 'Keraniganj', 0, true),
('Dhaka', 'Dhaka', 'Nawabganj', 0, true),
('Dhaka', 'Dhaka', 'Savar', 0, true),
('Dhaka', 'Gazipur', 'Gazipur Sadar', 0, true),
('Dhaka', 'Gazipur', 'Kaliakair', 0, true),
('Dhaka', 'Gazipur', 'Kaliganj', 0, true),
('Dhaka', 'Gazipur', 'Kapasia', 0, true),
('Dhaka', 'Gazipur', 'Sreepur', 0, true),
('Dhaka', 'Narayanganj', 'Araihazar', 0, true),
('Dhaka', 'Narayanganj', 'Bandar', 0, true),
('Dhaka', 'Narayanganj', 'Narayanganj Sadar', 0, true),
('Dhaka', 'Narayanganj', 'Rupganj', 0, true),
('Dhaka', 'Narayanganj', 'Sonargaon', 0, true),
('Dhaka', 'Narsingdi', 'Belabo', 0, true),
('Dhaka', 'Narsingdi', 'Monohardi', 0, true),
('Dhaka', 'Narsingdi', 'Narsingdi Sadar', 0, true),
('Dhaka', 'Narsingdi', 'Palash', 0, true),
('Dhaka', 'Narsingdi', 'Raipura', 0, true),
('Dhaka', 'Narsingdi', 'Shibpur', 0, true),
('Dhaka', 'Tangail', 'Basail', 0, true),
('Dhaka', 'Tangail', 'Bhuapur', 0, true),
('Dhaka', 'Tangail', 'Delduar', 0, true),
('Dhaka', 'Tangail', 'Dhanbari', 0, true),
('Dhaka', 'Tangail', 'Ghatail', 0, true),
('Dhaka', 'Tangail', 'Gopalpur', 0, true),
('Dhaka', 'Tangail', 'Kalihati', 0, true),
('Dhaka', 'Tangail', 'Madhupur', 0, true),
('Dhaka', 'Tangail', 'Mirzapur', 0, true),
('Dhaka', 'Tangail', 'Nagarpur', 0, true),
('Dhaka', 'Tangail', 'Sakhipur', 0, true),
('Dhaka', 'Tangail', 'Tangail Sadar', 0, true),
('Dhaka', 'Manikganj', 'Daulatpur', 0, true),
('Dhaka', 'Manikganj', 'Ghior', 0, true),
('Dhaka', 'Manikganj', 'Harirampur', 0, true),
('Dhaka', 'Manikganj', 'Manikganj Sadar', 0, true),
('Dhaka', 'Manikganj', 'Saturia', 0, true),
('Dhaka', 'Manikganj', 'Shibalaya', 0, true),
('Dhaka', 'Manikganj', 'Singair', 0, true),
('Dhaka', 'Munshiganj', 'Gazaria', 0, true),
('Dhaka', 'Munshiganj', 'Lohajang', 0, true),
('Dhaka', 'Munshiganj', 'Munshiganj Sadar', 0, true),
('Dhaka', 'Munshiganj', 'Sirajdikhan', 0, true),
('Dhaka', 'Munshiganj', 'Sreenagar', 0, true),
('Dhaka', 'Munshiganj', 'Tongibari', 0, true),
('Dhaka', 'Faridpur', 'Alfadanga', 0, true),
('Dhaka', 'Faridpur', 'Bhanga', 0, true),
('Dhaka', 'Faridpur', 'Boalmari', 0, true),
('Dhaka', 'Faridpur', 'Charbhadrasan', 0, true),
('Dhaka', 'Faridpur', 'Faridpur Sadar', 0, true),
('Dhaka', 'Faridpur', 'Madhukhali', 0, true),
('Dhaka', 'Faridpur', 'Nagarkanda', 0, true),
('Dhaka', 'Faridpur', 'Sadarpur', 0, true),
('Dhaka', 'Faridpur', 'Saltha', 0, true),
('Dhaka', 'Gopalganj', 'Gopalganj Sadar', 0, true),
('Dhaka', 'Gopalganj', 'Kashiani', 0, true),
('Dhaka', 'Gopalganj', 'Kotalipara', 0, true),
('Dhaka', 'Gopalganj', 'Muksudpur', 0, true),
('Dhaka', 'Gopalganj', 'Tungipara', 0, true),
('Dhaka', 'Madaripur', 'Kalkini', 0, true),
('Dhaka', 'Madaripur', 'Madaripur Sadar', 0, true),
('Dhaka', 'Madaripur', 'Rajoir', 0, true),
('Dhaka', 'Madaripur', 'Shibchar', 0, true),
('Dhaka', 'Rajbari', 'Baliakandi', 0, true),
('Dhaka', 'Rajbari', 'Goalandaghat', 0, true),
('Dhaka', 'Rajbari', 'Pangsha', 0, true),
('Dhaka', 'Rajbari', 'Rajbari Sadar', 0, true),
('Dhaka', 'Rajbari', 'Kalukhali', 0, true),
('Dhaka', 'Shariatpur', 'Bhedarganj', 0, true),
('Dhaka', 'Shariatpur', 'Damudya', 0, true),
('Dhaka', 'Shariatpur', 'Gosairhat', 0, true),
('Dhaka', 'Shariatpur', 'Naria', 0, true),
('Dhaka', 'Shariatpur', 'Shariatpur Sadar', 0, true),
('Dhaka', 'Shariatpur', 'Zajira', 0, true),
('Dhaka', 'Kishoreganj', 'Austagram', 0, true),
('Dhaka', 'Kishoreganj', 'Bajitpur', 0, true),
('Dhaka', 'Kishoreganj', 'Bhairab', 0, true),
('Dhaka', 'Kishoreganj', 'Hossainpur', 0, true),
('Dhaka', 'Kishoreganj', 'Itna', 0, true),
('Dhaka', 'Kishoreganj', 'Karimganj', 0, true),
('Dhaka', 'Kishoreganj', 'Katiadi', 0, true),
('Dhaka', 'Kishoreganj', 'Kishoreganj Sadar', 0, true),
('Dhaka', 'Kishoreganj', 'Kuliarchar', 0, true),
('Dhaka', 'Kishoreganj', 'Mithamain', 0, true),
('Dhaka', 'Kishoreganj', 'Nikli', 0, true),
('Dhaka', 'Kishoreganj', 'Pakundia', 0, true),
('Dhaka', 'Kishoreganj', 'Tarail', 0, true),
('Chattogram', 'Chattogram', 'Anwara', 0, true),
('Chattogram', 'Chattogram', 'Banshkhali', 0, true),
('Chattogram', 'Chattogram', 'Boalkhali', 0, true),
('Chattogram', 'Chattogram', 'Chandanaish', 0, true),
('Chattogram', 'Chattogram', 'Fatikchhari', 0, true),
('Chattogram', 'Chattogram', 'Hathazari', 0, true),
('Chattogram', 'Chattogram', 'Karnaphuli', 0, true),
('Chattogram', 'Chattogram', 'Lohagara', 0, true),
('Chattogram', 'Chattogram', 'Mirsharai', 0, true),
('Chattogram', 'Chattogram', 'Patiya', 0, true),
('Chattogram', 'Chattogram', 'Rangunia', 0, true),
('Chattogram', 'Chattogram', 'Raozan', 0, true),
('Chattogram', 'Chattogram', 'Sandwip', 0, true),
('Chattogram', 'Chattogram', 'Satkania', 0, true),
('Chattogram', 'Chattogram', 'Sitakunda', 0, true),
('Chattogram', 'Coxs Bazar', 'Chakaria', 0, true),
('Chattogram', 'Coxs Bazar', 'Coxs Bazar Sadar', 0, true),
('Chattogram', 'Coxs Bazar', 'Kutubdia', 0, true),
('Chattogram', 'Coxs Bazar', 'Maheshkhali', 0, true),
('Chattogram', 'Coxs Bazar', 'Pekua', 0, true),
('Chattogram', 'Coxs Bazar', 'Ramu', 0, true),
('Chattogram', 'Coxs Bazar', 'Teknaf', 0, true),
('Chattogram', 'Coxs Bazar', 'Ukhia', 0, true),
('Chattogram', 'Bandarban', 'Ali Kadam', 0, true),
('Chattogram', 'Bandarban', 'Bandarban Sadar', 0, true),
('Chattogram', 'Bandarban', 'Lama', 0, true),
('Chattogram', 'Bandarban', 'Naikhongchhari', 0, true),
('Chattogram', 'Bandarban', 'Rowangchhari', 0, true),
('Chattogram', 'Bandarban', 'Ruma', 0, true),
('Chattogram', 'Bandarban', 'Thanchi', 0, true),
('Chattogram', 'Rangamati', 'Baghaichhari', 0, true),
('Chattogram', 'Rangamati', 'Barkal', 0, true),
('Chattogram', 'Rangamati', 'Belaichhari', 0, true),
('Chattogram', 'Rangamati', 'Juraichhari', 0, true),
('Chattogram', 'Rangamati', 'Kaptai', 0, true),
('Chattogram', 'Rangamati', 'Kawkhali', 0, true),
('Chattogram', 'Rangamati', 'Langadu', 0, true),
('Chattogram', 'Rangamati', 'Naniarchar', 0, true),
('Chattogram', 'Rangamati', 'Rangamati Sadar', 0, true),
('Chattogram', 'Rangamati', 'Rajasthali', 0, true),
('Chattogram', 'Khagrachhari', 'Dighinala', 0, true),
('Chattogram', 'Khagrachhari', 'Khagrachhari Sadar', 0, true),
('Chattogram', 'Khagrachhari', 'Lakshmichhari', 0, true),
('Chattogram', 'Khagrachhari', 'Mahalchhari', 0, true),
('Chattogram', 'Khagrachhari', 'Manikchhari', 0, true),
('Chattogram', 'Khagrachhari', 'Matiranga', 0, true),
('Chattogram', 'Khagrachhari', 'Panchhari', 0, true),
('Chattogram', 'Khagrachhari', 'Ramgarh', 0, true),
('Chattogram', 'Feni', 'Chhagalnaiya', 0, true),
('Chattogram', 'Feni', 'Daganbhuiyan', 0, true),
('Chattogram', 'Feni', 'Feni Sadar', 0, true),
('Chattogram', 'Feni', 'Parshuram', 0, true),
('Chattogram', 'Feni', 'Sonagazi', 0, true),
('Chattogram', 'Feni', 'Fulgazi', 0, true),
('Chattogram', 'Noakhali', 'Begumganj', 0, true),
('Chattogram', 'Noakhali', 'Chatkhil', 0, true),
('Chattogram', 'Noakhali', 'Companiganj', 0, true),
('Chattogram', 'Noakhali', 'Hatiya', 0, true),
('Chattogram', 'Noakhali', 'Kabirhat', 0, true),
('Chattogram', 'Noakhali', 'Noakhali Sadar', 0, true),
('Chattogram', 'Noakhali', 'Senbagh', 0, true),
('Chattogram', 'Noakhali', 'Subarnachar', 0, true),
('Chattogram', 'Lakshmipur', 'Kamalnagar', 0, true),
('Chattogram', 'Lakshmipur', 'Lakshmipur Sadar', 0, true),
('Chattogram', 'Lakshmipur', 'Raipur', 0, true),
('Chattogram', 'Lakshmipur', 'Ramganj', 0, true),
('Chattogram', 'Lakshmipur', 'Ramgati', 0, true),
('Chattogram', 'Chandpur', 'Chandpur Sadar', 0, true),
('Chattogram', 'Chandpur', 'Faridganj', 0, true),
('Chattogram', 'Chandpur', 'Haimchar', 0, true),
('Chattogram', 'Chandpur', 'Hajiganj', 0, true),
('Chattogram', 'Chandpur', 'Kachua', 0, true),
('Chattogram', 'Chandpur', 'Matlab Dakshin', 0, true),
('Chattogram', 'Chandpur', 'Matlab Uttar', 0, true),
('Chattogram', 'Chandpur', 'Shahrasti', 0, true),
('Chattogram', 'Cumilla', 'Barura', 0, true),
('Chattogram', 'Cumilla', 'Brahmanpara', 0, true),
('Chattogram', 'Cumilla', 'Burichang', 0, true),
('Chattogram', 'Cumilla', 'Chandina', 0, true),
('Chattogram', 'Cumilla', 'Chauddagram', 0, true),
('Chattogram', 'Cumilla', 'Comilla Adarsha Sadar', 0, true),
('Chattogram', 'Cumilla', 'Comilla Sadar Dakshin', 0, true),
('Chattogram', 'Cumilla', 'Daudkandi', 0, true),
('Chattogram', 'Cumilla', 'Debidwar', 0, true),
('Chattogram', 'Cumilla', 'Homna', 0, true),
('Chattogram', 'Cumilla', 'Laksam', 0, true),
('Chattogram', 'Cumilla', 'Lalmai', 0, true),
('Chattogram', 'Cumilla', 'Meghna', 0, true),
('Chattogram', 'Cumilla', 'Monoharganj', 0, true),
('Chattogram', 'Cumilla', 'Muradnagar', 0, true),
('Chattogram', 'Cumilla', 'Nangalkot', 0, true),
('Chattogram', 'Cumilla', 'Titas', 0, true),
('Chattogram', 'Brahmanbaria', 'Akhaura', 0, true),
('Chattogram', 'Brahmanbaria', 'Ashuganj', 0, true),
('Chattogram', 'Brahmanbaria', 'Bancharampur', 0, true),
('Chattogram', 'Brahmanbaria', 'Bijoynagar', 0, true),
('Chattogram', 'Brahmanbaria', 'Brahmanbaria Sadar', 0, true),
('Chattogram', 'Brahmanbaria', 'Kasba', 0, true),
('Chattogram', 'Brahmanbaria', 'Nabinagar', 0, true),
('Chattogram', 'Brahmanbaria', 'Nasirnagar', 0, true),
('Chattogram', 'Brahmanbaria', 'Sarail', 0, true),
('Rajshahi', 'Rajshahi', 'Bagha', 0, true),
('Rajshahi', 'Rajshahi', 'Bagmara', 0, true),
('Rajshahi', 'Rajshahi', 'Charghat', 0, true),
('Rajshahi', 'Rajshahi', 'Durgapur', 0, true),
('Rajshahi', 'Rajshahi', 'Godagari', 0, true),
('Rajshahi', 'Rajshahi', 'Mohanpur', 0, true),
('Rajshahi', 'Rajshahi', 'Paba', 0, true),
('Rajshahi', 'Rajshahi', 'Puthia', 0, true),
('Rajshahi', 'Rajshahi', 'Tanore', 0, true),
('Rajshahi', 'Bogura', 'Adamdighi', 0, true),
('Rajshahi', 'Bogura', 'Bogura Sadar', 0, true),
('Rajshahi', 'Bogura', 'Dhunat', 0, true),
('Rajshahi', 'Bogura', 'Dhupchanchia', 0, true),
('Rajshahi', 'Bogura', 'Gabtali', 0, true),
('Rajshahi', 'Bogura', 'Kahaloo', 0, true),
('Rajshahi', 'Bogura', 'Nandigram', 0, true),
('Rajshahi', 'Bogura', 'Sariakandi', 0, true),
('Rajshahi', 'Bogura', 'Shajahanpur', 0, true),
('Rajshahi', 'Bogura', 'Sherpur', 0, true),
('Rajshahi', 'Bogura', 'Shibganj', 0, true),
('Rajshahi', 'Bogura', 'Sonatala', 0, true),
('Rajshahi', 'Joypurhat', 'Akkelpur', 0, true),
('Rajshahi', 'Joypurhat', 'Joypurhat Sadar', 0, true),
('Rajshahi', 'Joypurhat', 'Kalai', 0, true),
('Rajshahi', 'Joypurhat', 'Khetlal', 0, true),
('Rajshahi', 'Joypurhat', 'Panchbibi', 0, true),
('Rajshahi', 'Naogaon', 'Atrai', 0, true),
('Rajshahi', 'Naogaon', 'Badalgachhi', 0, true),
('Rajshahi', 'Naogaon', 'Dhamoirhat', 0, true),
('Rajshahi', 'Naogaon', 'Manda', 0, true),
('Rajshahi', 'Naogaon', 'Mahadebpur', 0, true),
('Rajshahi', 'Naogaon', 'Naogaon Sadar', 0, true),
('Rajshahi', 'Naogaon', 'Niamatpur', 0, true),
('Rajshahi', 'Naogaon', 'Patnitala', 0, true),
('Rajshahi', 'Naogaon', 'Porsha', 0, true),
('Rajshahi', 'Naogaon', 'Raninagar', 0, true),
('Rajshahi', 'Naogaon', 'Sapahar', 0, true),
('Rajshahi', 'Natore', 'Bagatipara', 0, true),
('Rajshahi', 'Natore', 'Baraigram', 0, true),
('Rajshahi', 'Natore', 'Gurudaspur', 0, true),
('Rajshahi', 'Natore', 'Lalpur', 0, true),
('Rajshahi', 'Natore', 'Natore Sadar', 0, true),
('Rajshahi', 'Natore', 'Singra', 0, true),
('Rajshahi', 'Natore', 'Naldanga', 0, true),
('Rajshahi', 'Chapainawabganj', 'Bholahat', 0, true),
('Rajshahi', 'Chapainawabganj', 'Chapainawabganj Sadar', 0, true),
('Rajshahi', 'Chapainawabganj', 'Gomastapur', 0, true),
('Rajshahi', 'Chapainawabganj', 'Nachole', 0, true),
('Rajshahi', 'Chapainawabganj', 'Shibganj', 0, true),
('Rajshahi', 'Pabna', 'Atgharia', 0, true),
('Rajshahi', 'Pabna', 'Bera', 0, true),
('Rajshahi', 'Pabna', 'Bhangura', 0, true),
('Rajshahi', 'Pabna', 'Chatmohar', 0, true),
('Rajshahi', 'Pabna', 'Faridpur', 0, true),
('Rajshahi', 'Pabna', 'Ishwardi', 0, true),
('Rajshahi', 'Pabna', 'Pabna Sadar', 0, true),
('Rajshahi', 'Pabna', 'Santhia', 0, true),
('Rajshahi', 'Pabna', 'Sujanagar', 0, true),
('Rajshahi', 'Sirajganj', 'Belkuchi', 0, true),
('Rajshahi', 'Sirajganj', 'Chauhali', 0, true),
('Rajshahi', 'Sirajganj', 'Kamarkhanda', 0, true),
('Rajshahi', 'Sirajganj', 'Kazipur', 0, true),
('Rajshahi', 'Sirajganj', 'Raiganj', 0, true),
('Rajshahi', 'Sirajganj', 'Shahjadpur', 0, true),
('Rajshahi', 'Sirajganj', 'Sirajganj Sadar', 0, true),
('Rajshahi', 'Sirajganj', 'Tarash', 0, true),
('Rajshahi', 'Sirajganj', 'Ullapara', 0, true),
('Khulna', 'Khulna', 'Batiaghata', 0, true),
('Khulna', 'Khulna', 'Dacope', 0, true),
('Khulna', 'Khulna', 'Dighalia', 0, true),
('Khulna', 'Khulna', 'Dumuria', 0, true),
('Khulna', 'Khulna', 'Koyra', 0, true),
('Khulna', 'Khulna', 'Paikgachha', 0, true),
('Khulna', 'Khulna', 'Phultala', 0, true),
('Khulna', 'Khulna', 'Rupsha', 0, true),
('Khulna', 'Khulna', 'Terokhada', 0, true),
('Khulna', 'Jashore', 'Abhaynagar', 0, true),
('Khulna', 'Jashore', 'Bagherpara', 0, true),
('Khulna', 'Jashore', 'Chaugachha', 0, true),
('Khulna', 'Jashore', 'Jashore Sadar', 0, true),
('Khulna', 'Jashore', 'Jhikargachha', 0, true),
('Khulna', 'Jashore', 'Keshabpur', 0, true),
('Khulna', 'Jashore', 'Manirampur', 0, true),
('Khulna', 'Jashore', 'Sharsha', 0, true),
('Khulna', 'Satkhira', 'Assasuni', 0, true),
('Khulna', 'Satkhira', 'Debhata', 0, true),
('Khulna', 'Satkhira', 'Kaliganj', 0, true),
('Khulna', 'Satkhira', 'Kalaroa', 0, true),
('Khulna', 'Satkhira', 'Satkhira Sadar', 0, true),
('Khulna', 'Satkhira', 'Shyamnagar', 0, true),
('Khulna', 'Satkhira', 'Tala', 0, true),
('Khulna', 'Bagerhat', 'Bagerhat Sadar', 0, true),
('Khulna', 'Bagerhat', 'Chitalmari', 0, true),
('Khulna', 'Bagerhat', 'Fakirhat', 0, true),
('Khulna', 'Bagerhat', 'Kachua', 0, true),
('Khulna', 'Bagerhat', 'Mollahat', 0, true),
('Khulna', 'Bagerhat', 'Mongla', 0, true),
('Khulna', 'Bagerhat', 'Morrelganj', 0, true),
('Khulna', 'Bagerhat', 'Rampal', 0, true),
('Khulna', 'Bagerhat', 'Sarankhola', 0, true),
('Khulna', 'Narail', 'Kalia', 0, true),
('Khulna', 'Narail', 'Lohagara', 0, true),
('Khulna', 'Narail', 'Narail Sadar', 0, true),
('Khulna', 'Jhenaidah', 'Harinakunda', 0, true),
('Khulna', 'Jhenaidah', 'Jhenaidah Sadar', 0, true),
('Khulna', 'Jhenaidah', 'Kaliganj', 0, true),
('Khulna', 'Jhenaidah', 'Kotchandpur', 0, true),
('Khulna', 'Jhenaidah', 'Maheshpur', 0, true),
('Khulna', 'Jhenaidah', 'Shailkupa', 0, true),
('Khulna', 'Magura', 'Magura Sadar', 0, true),
('Khulna', 'Magura', 'Mohammadpur', 0, true),
('Khulna', 'Magura', 'Shalikha', 0, true),
('Khulna', 'Magura', 'Sreepur', 0, true),
('Khulna', 'Kushtia', 'Bheramara', 0, true),
('Khulna', 'Kushtia', 'Daulatpur', 0, true),
('Khulna', 'Kushtia', 'Khoksa', 0, true),
('Khulna', 'Kushtia', 'Kumarkhali', 0, true),
('Khulna', 'Kushtia', 'Kushtia Sadar', 0, true),
('Khulna', 'Kushtia', 'Mirpur', 0, true),
('Khulna', 'Chuadanga', 'Alamdanga', 0, true),
('Khulna', 'Chuadanga', 'Chuadanga Sadar', 0, true),
('Khulna', 'Chuadanga', 'Damurhuda', 0, true),
('Khulna', 'Chuadanga', 'Jibannagar', 0, true),
('Khulna', 'Meherpur', 'Gangni', 0, true),
('Khulna', 'Meherpur', 'Meherpur Sadar', 0, true),
('Khulna', 'Meherpur', 'Mujibnagar', 0, true),
('Barishal', 'Barishal', 'Agailjhara', 0, true),
('Barishal', 'Barishal', 'Babuganj', 0, true),
('Barishal', 'Barishal', 'Bakerganj', 0, true),
('Barishal', 'Barishal', 'Banaripara', 0, true),
('Barishal', 'Barishal', 'Gaurnadi', 0, true),
('Barishal', 'Barishal', 'Hizla', 0, true),
('Barishal', 'Barishal', 'Barishal Sadar', 0, true),
('Barishal', 'Barishal', 'Mehendiganj', 0, true),
('Barishal', 'Barishal', 'Muladi', 0, true),
('Barishal', 'Barishal', 'Wazirpur', 0, true),
('Barishal', 'Bhola', 'Bhola Sadar', 0, true),
('Barishal', 'Bhola', 'Burhanuddin', 0, true),
('Barishal', 'Bhola', 'Char Fasson', 0, true),
('Barishal', 'Bhola', 'Daulatkhan', 0, true),
('Barishal', 'Bhola', 'Lalmohan', 0, true),
('Barishal', 'Bhola', 'Manpura', 0, true),
('Barishal', 'Bhola', 'Tazumuddin', 0, true),
('Barishal', 'Patuakhali', 'Bauphal', 0, true),
('Barishal', 'Patuakhali', 'Dashmina', 0, true),
('Barishal', 'Patuakhali', 'Dumki', 0, true),
('Barishal', 'Patuakhali', 'Galachipa', 0, true),
('Barishal', 'Patuakhali', 'Kalapara', 0, true),
('Barishal', 'Patuakhali', 'Mirzaganj', 0, true),
('Barishal', 'Patuakhali', 'Patuakhali Sadar', 0, true),
('Barishal', 'Patuakhali', 'Rangabali', 0, true),
('Barishal', 'Pirojpur', 'Bhandaria', 0, true),
('Barishal', 'Pirojpur', 'Kawkhali', 0, true),
('Barishal', 'Pirojpur', 'Mathbaria', 0, true),
('Barishal', 'Pirojpur', 'Nazirpur', 0, true),
('Barishal', 'Pirojpur', 'Nesarabad (Swarupkathi)', 0, true),
('Barishal', 'Pirojpur', 'Pirojpur Sadar', 0, true),
('Barishal', 'Pirojpur', 'Zianagar', 0, true),
('Barishal', 'Jhalokathi', 'Jhalokathi Sadar', 0, true),
('Barishal', 'Jhalokathi', 'Kathalia', 0, true),
('Barishal', 'Jhalokathi', 'Nalchity', 0, true),
('Barishal', 'Jhalokathi', 'Rajapur', 0, true),
('Barishal', 'Barguna', 'Amtali', 0, true),
('Barishal', 'Barguna', 'Bamna', 0, true),
('Barishal', 'Barguna', 'Barguna Sadar', 0, true),
('Barishal', 'Barguna', 'Betagi', 0, true),
('Barishal', 'Barguna', 'Patharghata', 0, true),
('Barishal', 'Barguna', 'Taltali', 0, true),
('Sylhet', 'Sylhet', 'Balaganj', 0, true),
('Sylhet', 'Sylhet', 'Beanibazar', 0, true),
('Sylhet', 'Sylhet', 'Bishwanath', 0, true),
('Sylhet', 'Sylhet', 'Companiganj', 0, true),
('Sylhet', 'Sylhet', 'Dakshin Surma', 0, true),
('Sylhet', 'Sylhet', 'Fenchuganj', 0, true),
('Sylhet', 'Sylhet', 'Golapganj', 0, true),
('Sylhet', 'Sylhet', 'Gowainghat', 0, true),
('Sylhet', 'Sylhet', 'Jaintiapur', 0, true),
('Sylhet', 'Sylhet', 'Kanaighat', 0, true),
('Sylhet', 'Sylhet', 'Sylhet Sadar', 0, true),
('Sylhet', 'Sylhet', 'Zakiganj', 0, true),
('Sylhet', 'Moulvibazar', 'Barlekha', 0, true),
('Sylhet', 'Moulvibazar', 'Juri', 0, true),
('Sylhet', 'Moulvibazar', 'Kamalganj', 0, true),
('Sylhet', 'Moulvibazar', 'Kulaura', 0, true),
('Sylhet', 'Moulvibazar', 'Moulvibazar Sadar', 0, true),
('Sylhet', 'Moulvibazar', 'Rajnagar', 0, true),
('Sylhet', 'Moulvibazar', 'Sreemangal', 0, true),
('Sylhet', 'Habiganj', 'Ajmiriganj', 0, true),
('Sylhet', 'Habiganj', 'Bahubal', 0, true),
('Sylhet', 'Habiganj', 'Baniachong', 0, true),
('Sylhet', 'Habiganj', 'Chunarughat', 0, true),
('Sylhet', 'Habiganj', 'Habiganj Sadar', 0, true),
('Sylhet', 'Habiganj', 'Lakhai', 0, true),
('Sylhet', 'Habiganj', 'Madhabpur', 0, true),
('Sylhet', 'Habiganj', 'Nabiganj', 0, true),
('Sylhet', 'Sunamganj', 'Bishwambarpur', 0, true),
('Sylhet', 'Sunamganj', 'Chhatak', 0, true),
('Sylhet', 'Sunamganj', 'Dakshin Sunamganj', 0, true),
('Sylhet', 'Sunamganj', 'Derai', 0, true),
('Sylhet', 'Sunamganj', 'Dharampasha', 0, true),
('Sylhet', 'Sunamganj', 'Dowarabazar', 0, true),
('Sylhet', 'Sunamganj', 'Jagannathpur', 0, true),
('Sylhet', 'Sunamganj', 'Jamalganj', 0, true),
('Sylhet', 'Sunamganj', 'Sunamganj Sadar', 0, true),
('Sylhet', 'Sunamganj', 'Shalla', 0, true),
('Sylhet', 'Sunamganj', 'Tahirpur', 0, true),
('Rangpur', 'Rangpur', 'Badarganj', 0, true),
('Rangpur', 'Rangpur', 'Gangachara', 0, true),
('Rangpur', 'Rangpur', 'Kaunia', 0, true),
('Rangpur', 'Rangpur', 'Rangpur Sadar', 0, true),
('Rangpur', 'Rangpur', 'Mithapukur', 0, true),
('Rangpur', 'Rangpur', 'Pirgachha', 0, true),
('Rangpur', 'Rangpur', 'Pirganj', 0, true),
('Rangpur', 'Rangpur', 'Taraganj', 0, true),
('Rangpur', 'Dinajpur', 'Birampur', 0, true),
('Rangpur', 'Dinajpur', 'Birganj', 0, true),
('Rangpur', 'Dinajpur', 'Biral', 0, true),
('Rangpur', 'Dinajpur', 'Bochaganj', 0, true),
('Rangpur', 'Dinajpur', 'Chirirbandar', 0, true),
('Rangpur', 'Dinajpur', 'Dinajpur Sadar', 0, true),
('Rangpur', 'Dinajpur', 'Ghoraghat', 0, true),
('Rangpur', 'Dinajpur', 'Hakimpur', 0, true),
('Rangpur', 'Dinajpur', 'Kaharole', 0, true),
('Rangpur', 'Dinajpur', 'Khansama', 0, true),
('Rangpur', 'Dinajpur', 'Nawabganj', 0, true),
('Rangpur', 'Dinajpur', 'Parbatipur', 0, true),
('Rangpur', 'Thakurgaon', 'Baliadangi', 0, true),
('Rangpur', 'Thakurgaon', 'Haripur', 0, true),
('Rangpur', 'Thakurgaon', 'Pirganj', 0, true),
('Rangpur', 'Thakurgaon', 'Ranishankail', 0, true),
('Rangpur', 'Thakurgaon', 'Thakurgaon Sadar', 0, true),
('Rangpur', 'Panchagarh', 'Atwari', 0, true),
('Rangpur', 'Panchagarh', 'Boda', 0, true),
('Rangpur', 'Panchagarh', 'Debiganj', 0, true),
('Rangpur', 'Panchagarh', 'Panchagarh Sadar', 0, true),
('Rangpur', 'Panchagarh', 'Tetulia', 0, true),
('Rangpur', 'Nilphamari', 'Dimla', 0, true),
('Rangpur', 'Nilphamari', 'Domar', 0, true),
('Rangpur', 'Nilphamari', 'Jaldhaka', 0, true),
('Rangpur', 'Nilphamari', 'Kishoreganj', 0, true),
('Rangpur', 'Nilphamari', 'Nilphamari Sadar', 0, true),
('Rangpur', 'Nilphamari', 'Saidpur', 0, true),
('Rangpur', 'Lalmonirhat', 'Aditmari', 0, true),
('Rangpur', 'Lalmonirhat', 'Hatibandha', 0, true),
('Rangpur', 'Lalmonirhat', 'Kaliganj', 0, true),
('Rangpur', 'Lalmonirhat', 'Lalmonirhat Sadar', 0, true),
('Rangpur', 'Lalmonirhat', 'Patgram', 0, true),
('Rangpur', 'Kurigram', 'Bhurungamari', 0, true),
('Rangpur', 'Kurigram', 'Char Rajibpur', 0, true),
('Rangpur', 'Kurigram', 'Chilmari', 0, true),
('Rangpur', 'Kurigram', 'Fulbari', 0, true),
('Rangpur', 'Kurigram', 'Kurigram Sadar', 0, true),
('Rangpur', 'Kurigram', 'Nageshwari', 0, true),
('Rangpur', 'Kurigram', 'Rajarhat', 0, true),
('Rangpur', 'Kurigram', 'Raumari', 0, true),
('Rangpur', 'Kurigram', 'Ulipur', 0, true),
('Rangpur', 'Gaibandha', 'Fulchhari', 0, true),
('Rangpur', 'Gaibandha', 'Gaibandha Sadar', 0, true),
('Rangpur', 'Gaibandha', 'Gobindaganj', 0, true),
('Rangpur', 'Gaibandha', 'Palashbari', 0, true),
('Rangpur', 'Gaibandha', 'Sadullapur', 0, true),
('Rangpur', 'Gaibandha', 'Sundarganj', 0, true),
('Mymensingh', 'Mymensingh', 'Bhaluka', 0, true),
('Mymensingh', 'Mymensingh', 'Dhobaura', 0, true),
('Mymensingh', 'Mymensingh', 'Fulbaria', 0, true),
('Mymensingh', 'Mymensingh', 'Gaffargaon', 0, true),
('Mymensingh', 'Mymensingh', 'Gauripur', 0, true),
('Mymensingh', 'Mymensingh', 'Haluaghat', 0, true),
('Mymensingh', 'Mymensingh', 'Ishwarganj', 0, true),
('Mymensingh', 'Mymensingh', 'Mymensingh Sadar', 0, true),
('Mymensingh', 'Mymensingh', 'Muktagachha', 0, true),
('Mymensingh', 'Mymensingh', 'Nandail', 0, true),
('Mymensingh', 'Mymensingh', 'Phulpur', 0, true),
('Mymensingh', 'Mymensingh', 'Trishal', 0, true),
('Mymensingh', 'Jamalpur', 'Bakshiganj', 0, true),
('Mymensingh', 'Jamalpur', 'Dewanganj', 0, true),
('Mymensingh', 'Jamalpur', 'Islampur', 0, true),
('Mymensingh', 'Jamalpur', 'Jamalpur Sadar', 0, true),
('Mymensingh', 'Jamalpur', 'Madarganj', 0, true),
('Mymensingh', 'Jamalpur', 'Melandaha', 0, true),
('Mymensingh', 'Jamalpur', 'Sarishabari', 0, true),
('Mymensingh', 'Netrokona', 'Atpara', 0, true),
('Mymensingh', 'Netrokona', 'Barhatta', 0, true),
('Mymensingh', 'Netrokona', 'Durgapur', 0, true),
('Mymensingh', 'Netrokona', 'Kalmakanda', 0, true),
('Mymensingh', 'Netrokona', 'Kendua', 0, true),
('Mymensingh', 'Netrokona', 'Khaliajuri', 0, true),
('Mymensingh', 'Netrokona', 'Madan', 0, true),
('Mymensingh', 'Netrokona', 'Mohanganj', 0, true),
('Mymensingh', 'Netrokona', 'Netrokona Sadar', 0, true),
('Mymensingh', 'Netrokona', 'Purbadhala', 0, true),
('Mymensingh', 'Sherpur', 'Jhenaigati', 0, true),
('Mymensingh', 'Sherpur', 'Nakla', 0, true),
('Mymensingh', 'Sherpur', 'Nalitabari', 0, true),
('Mymensingh', 'Sherpur', 'Sherpur Sadar', 0, true),
('Mymensingh', 'Sherpur', 'Sreebardi', 0, true);