-- Step 1: Add is_active column to delivery_zones
ALTER TABLE public.delivery_zones
ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;

-- Step 2: Bulk insert all Bangladesh divisions, districts, upazilas with 120 taka charge

INSERT INTO public.delivery_zones (division, zilla, upazilla, charge, is_active) VALUES

-- ============================================================
-- 1. DHAKA DIVISION
-- ============================================================
-- Dhaka District
('Dhaka', 'Dhaka', 'Dhamrai', 120, true),
('Dhaka', 'Dhaka', 'Dohar', 120, true),
('Dhaka', 'Dhaka', 'Keraniganj', 120, true),
('Dhaka', 'Dhaka', 'Nawabganj', 120, true),
('Dhaka', 'Dhaka', 'Savar', 120, true),
-- Gazipur District
('Dhaka', 'Gazipur', 'Gazipur Sadar', 120, true),
('Dhaka', 'Gazipur', 'Kaliakair', 120, true),
('Dhaka', 'Gazipur', 'Kaliganj', 120, true),
('Dhaka', 'Gazipur', 'Kapasia', 120, true),
('Dhaka', 'Gazipur', 'Sreepur', 120, true),
-- Narayanganj District
('Dhaka', 'Narayanganj', 'Araihazar', 120, true),
('Dhaka', 'Narayanganj', 'Bandar', 120, true),
('Dhaka', 'Narayanganj', 'Narayanganj Sadar', 120, true),
('Dhaka', 'Narayanganj', 'Rupganj', 120, true),
('Dhaka', 'Narayanganj', 'Sonargaon', 120, true),
-- Narsingdi District
('Dhaka', 'Narsingdi', 'Belabo', 120, true),
('Dhaka', 'Narsingdi', 'Monohardi', 120, true),
('Dhaka', 'Narsingdi', 'Narsingdi Sadar', 120, true),
('Dhaka', 'Narsingdi', 'Palash', 120, true),
('Dhaka', 'Narsingdi', 'Raipura', 120, true),
('Dhaka', 'Narsingdi', 'Shibpur', 120, true),
-- Tangail District
('Dhaka', 'Tangail', 'Basail', 120, true),
('Dhaka', 'Tangail', 'Bhuapur', 120, true),
('Dhaka', 'Tangail', 'Delduar', 120, true),
('Dhaka', 'Tangail', 'Dhanbari', 120, true),
('Dhaka', 'Tangail', 'Ghatail', 120, true),
('Dhaka', 'Tangail', 'Gopalpur', 120, true),
('Dhaka', 'Tangail', 'Kalihati', 120, true),
('Dhaka', 'Tangail', 'Madhupur', 120, true),
('Dhaka', 'Tangail', 'Mirzapur', 120, true),
('Dhaka', 'Tangail', 'Nagarpur', 120, true),
('Dhaka', 'Tangail', 'Sakhipur', 120, true),
('Dhaka', 'Tangail', 'Tangail Sadar', 120, true),
-- Manikganj District
('Dhaka', 'Manikganj', 'Daulatpur', 120, true),
('Dhaka', 'Manikganj', 'Ghior', 120, true),
('Dhaka', 'Manikganj', 'Harirampur', 120, true),
('Dhaka', 'Manikganj', 'Manikganj Sadar', 120, true),
('Dhaka', 'Manikganj', 'Saturia', 120, true),
('Dhaka', 'Manikganj', 'Shibalaya', 120, true),
('Dhaka', 'Manikganj', 'Singair', 120, true),
-- Munshiganj District
('Dhaka', 'Munshiganj', 'Gazaria', 120, true),
('Dhaka', 'Munshiganj', 'Lohajang', 120, true),
('Dhaka', 'Munshiganj', 'Munshiganj Sadar', 120, true),
('Dhaka', 'Munshiganj', 'Sirajdikhan', 120, true),
('Dhaka', 'Munshiganj', 'Sreenagar', 120, true),
('Dhaka', 'Munshiganj', 'Tongibari', 120, true),
-- Faridpur District
('Dhaka', 'Faridpur', 'Alfadanga', 120, true),
('Dhaka', 'Faridpur', 'Bhanga', 120, true),
('Dhaka', 'Faridpur', 'Boalmari', 120, true),
('Dhaka', 'Faridpur', 'Charbhadrasan', 120, true),
('Dhaka', 'Faridpur', 'Faridpur Sadar', 120, true),
('Dhaka', 'Faridpur', 'Madhukhali', 120, true),
('Dhaka', 'Faridpur', 'Nagarkanda', 120, true),
('Dhaka', 'Faridpur', 'Sadarpur', 120, true),
('Dhaka', 'Faridpur', 'Saltha', 120, true),
-- Gopalganj District
('Dhaka', 'Gopalganj', 'Gopalganj Sadar', 120, true),
('Dhaka', 'Gopalganj', 'Kashiani', 120, true),
('Dhaka', 'Gopalganj', 'Kotalipara', 120, true),
('Dhaka', 'Gopalganj', 'Muksudpur', 120, true),
('Dhaka', 'Gopalganj', 'Tungipara', 120, true),
-- Madaripur District
('Dhaka', 'Madaripur', 'Kalkini', 120, true),
('Dhaka', 'Madaripur', 'Madaripur Sadar', 120, true),
('Dhaka', 'Madaripur', 'Rajoir', 120, true),
('Dhaka', 'Madaripur', 'Shibchar', 120, true),
-- Rajbari District
('Dhaka', 'Rajbari', 'Baliakandi', 120, true),
('Dhaka', 'Rajbari', 'Goalandaghat', 120, true),
('Dhaka', 'Rajbari', 'Pangsha', 120, true),
('Dhaka', 'Rajbari', 'Rajbari Sadar', 120, true),
('Dhaka', 'Rajbari', 'Kalukhali', 120, true),
-- Shariatpur District
('Dhaka', 'Shariatpur', 'Bhedarganj', 120, true),
('Dhaka', 'Shariatpur', 'Damudya', 120, true),
('Dhaka', 'Shariatpur', 'Gosairhat', 120, true),
('Dhaka', 'Shariatpur', 'Naria', 120, true),
('Dhaka', 'Shariatpur', 'Shariatpur Sadar', 120, true),
('Dhaka', 'Shariatpur', 'Zajira', 120, true),
-- Kishoreganj District
('Dhaka', 'Kishoreganj', 'Austagram', 120, true),
('Dhaka', 'Kishoreganj', 'Bajitpur', 120, true),
('Dhaka', 'Kishoreganj', 'Bhairab', 120, true),
('Dhaka', 'Kishoreganj', 'Hossainpur', 120, true),
('Dhaka', 'Kishoreganj', 'Itna', 120, true),
('Dhaka', 'Kishoreganj', 'Karimganj', 120, true),
('Dhaka', 'Kishoreganj', 'Katiadi', 120, true),
('Dhaka', 'Kishoreganj', 'Kishoreganj Sadar', 120, true),
('Dhaka', 'Kishoreganj', 'Kuliarchar', 120, true),
('Dhaka', 'Kishoreganj', 'Mithamain', 120, true),
('Dhaka', 'Kishoreganj', 'Nikli', 120, true),
('Dhaka', 'Kishoreganj', 'Pakundia', 120, true),
('Dhaka', 'Kishoreganj', 'Tarail', 120, true),

-- ============================================================
-- 2. CHATTOGRAM DIVISION
-- ============================================================
-- Chattogram District
('Chattogram', 'Chattogram', 'Anwara', 120, true),
('Chattogram', 'Chattogram', 'Banshkhali', 120, true),
('Chattogram', 'Chattogram', 'Boalkhali', 120, true),
('Chattogram', 'Chattogram', 'Chandanaish', 120, true),
('Chattogram', 'Chattogram', 'Fatikchhari', 120, true),
('Chattogram', 'Chattogram', 'Hathazari', 120, true),
('Chattogram', 'Chattogram', 'Karnaphuli', 120, true),
('Chattogram', 'Chattogram', 'Lohagara', 120, true),
('Chattogram', 'Chattogram', 'Mirsharai', 120, true),
('Chattogram', 'Chattogram', 'Patiya', 120, true),
('Chattogram', 'Chattogram', 'Rangunia', 120, true),
('Chattogram', 'Chattogram', 'Raozan', 120, true),
('Chattogram', 'Chattogram', 'Sandwip', 120, true),
('Chattogram', 'Chattogram', 'Satkania', 120, true),
('Chattogram', 'Chattogram', 'Sitakunda', 120, true),
-- Cox''s Bazar District
('Chattogram', 'Cox''s Bazar', 'Chakaria', 120, true),
('Chattogram', 'Cox''s Bazar', 'Cox''s Bazar Sadar', 120, true),
('Chattogram', 'Cox''s Bazar', 'Kutubdia', 120, true),
('Chattogram', 'Cox''s Bazar', 'Maheshkhali', 120, true),
('Chattogram', 'Cox''s Bazar', 'Pekua', 120, true),
('Chattogram', 'Cox''s Bazar', 'Ramu', 120, true),
('Chattogram', 'Cox''s Bazar', 'Teknaf', 120, true),
('Chattogram', 'Cox''s Bazar', 'Ukhia', 120, true),
-- Bandarban District
('Chattogram', 'Bandarban', 'Ali Kadam', 120, true),
('Chattogram', 'Bandarban', 'Bandarban Sadar', 120, true),
('Chattogram', 'Bandarban', 'Lama', 120, true),
('Chattogram', 'Bandarban', 'Naikhongchhari', 120, true),
('Chattogram', 'Bandarban', 'Rowangchhari', 120, true),
('Chattogram', 'Bandarban', 'Ruma', 120, true),
('Chattogram', 'Bandarban', 'Thanchi', 120, true),
-- Rangamati District
('Chattogram', 'Rangamati', 'Baghaichhari', 120, true),
('Chattogram', 'Rangamati', 'Barkal', 120, true),
('Chattogram', 'Rangamati', 'Belaichhari', 120, true),
('Chattogram', 'Rangamati', 'Juraichhari', 120, true),
('Chattogram', 'Rangamati', 'Kaptai', 120, true),
('Chattogram', 'Rangamati', 'Kawkhali', 120, true),
('Chattogram', 'Rangamati', 'Langadu', 120, true),
('Chattogram', 'Rangamati', 'Naniarchar', 120, true),
('Chattogram', 'Rangamati', 'Rangamati Sadar', 120, true),
('Chattogram', 'Rangamati', 'Rajasthali', 120, true),
-- Khagrachhari District
('Chattogram', 'Khagrachhari', 'Dighinala', 120, true),
('Chattogram', 'Khagrachhari', 'Khagrachhari Sadar', 120, true),
('Chattogram', 'Khagrachhari', 'Lakshmichhari', 120, true),
('Chattogram', 'Khagrachhari', 'Mahalchhari', 120, true),
('Chattogram', 'Khagrachhari', 'Manikchhari', 120, true),
('Chattogram', 'Khagrachhari', 'Matiranga', 120, true),
('Chattogram', 'Khagrachhari', 'Panchhari', 120, true),
('Chattogram', 'Khagrachhari', 'Ramgarh', 120, true),
-- Feni District
('Chattogram', 'Feni', 'Chhagalnaiya', 120, true),
('Chattogram', 'Feni', 'Daganbhuiyan', 120, true),
('Chattogram', 'Feni', 'Feni Sadar', 120, true),
('Chattogram', 'Feni', 'Parshuram', 120, true),
('Chattogram', 'Feni', 'Sonagazi', 120, true),
('Chattogram', 'Feni', 'Fulgazi', 120, true),
-- Noakhali District
('Chattogram', 'Noakhali', 'Begumganj', 120, true),
('Chattogram', 'Noakhali', 'Chatkhil', 120, true),
('Chattogram', 'Noakhali', 'Companiganj', 120, true),
('Chattogram', 'Noakhali', 'Hatiya', 120, true),
('Chattogram', 'Noakhali', 'Kabirhat', 120, true),
('Chattogram', 'Noakhali', 'Noakhali Sadar', 120, true),
('Chattogram', 'Noakhali', 'Senbagh', 120, true),
('Chattogram', 'Noakhali', 'Subarnachar', 120, true),
-- Lakshmipur District
('Chattogram', 'Lakshmipur', 'Kamalnagar', 120, true),
('Chattogram', 'Lakshmipur', 'Lakshmipur Sadar', 120, true),
('Chattogram', 'Lakshmipur', 'Raipur', 120, true),
('Chattogram', 'Lakshmipur', 'Ramganj', 120, true),
('Chattogram', 'Lakshmipur', 'Ramgati', 120, true),
-- Chandpur District
('Chattogram', 'Chandpur', 'Chandpur Sadar', 120, true),
('Chattogram', 'Chandpur', 'Faridganj', 120, true),
('Chattogram', 'Chandpur', 'Haimchar', 120, true),
('Chattogram', 'Chandpur', 'Hajiganj', 120, true),
('Chattogram', 'Chandpur', 'Kachua', 120, true),
('Chattogram', 'Chandpur', 'Matlab Dakshin', 120, true),
('Chattogram', 'Chandpur', 'Matlab Uttar', 120, true),
('Chattogram', 'Chandpur', 'Shahrasti', 120, true),
-- Cumilla District
('Chattogram', 'Cumilla', 'Barura', 120, true),
('Chattogram', 'Cumilla', 'Brahmanpara', 120, true),
('Chattogram', 'Cumilla', 'Burichang', 120, true),
('Chattogram', 'Cumilla', 'Chandina', 120, true),
('Chattogram', 'Cumilla', 'Chauddagram', 120, true),
('Chattogram', 'Cumilla', 'Comilla Adarsha Sadar', 120, true),
('Chattogram', 'Cumilla', 'Comilla Sadar Dakshin', 120, true),
('Chattogram', 'Cumilla', 'Daudkandi', 120, true),
('Chattogram', 'Cumilla', 'Debidwar', 120, true),
('Chattogram', 'Cumilla', 'Homna', 120, true),
('Chattogram', 'Cumilla', 'Laksam', 120, true),
('Chattogram', 'Cumilla', 'Lalmai', 120, true),
('Chattogram', 'Cumilla', 'Meghna', 120, true),
('Chattogram', 'Cumilla', 'Monoharganj', 120, true),
('Chattogram', 'Cumilla', 'Muradnagar', 120, true),
('Chattogram', 'Cumilla', 'Nangalkot', 120, true),
('Chattogram', 'Cumilla', 'Titas', 120, true),
-- Brahmanbaria District
('Chattogram', 'Brahmanbaria', 'Akhaura', 120, true),
('Chattogram', 'Brahmanbaria', 'Ashuganj', 120, true),
('Chattogram', 'Brahmanbaria', 'Bancharampur', 120, true),
('Chattogram', 'Brahmanbaria', 'Bijoynagar', 120, true),
('Chattogram', 'Brahmanbaria', 'Brahmanbaria Sadar', 120, true),
('Chattogram', 'Brahmanbaria', 'Kasba', 120, true),
('Chattogram', 'Brahmanbaria', 'Nabinagar', 120, true),
('Chattogram', 'Brahmanbaria', 'Nasirnagar', 120, true),
('Chattogram', 'Brahmanbaria', 'Sarail', 120, true),

-- ============================================================
-- 3. RAJSHAHI DIVISION
-- ============================================================
-- Rajshahi District
('Rajshahi', 'Rajshahi', 'Bagha', 120, true),
('Rajshahi', 'Rajshahi', 'Bagmara', 120, true),
('Rajshahi', 'Rajshahi', 'Charghat', 120, true),
('Rajshahi', 'Rajshahi', 'Durgapur', 120, true),
('Rajshahi', 'Rajshahi', 'Godagari', 120, true),
('Rajshahi', 'Rajshahi', 'Mohanpur', 120, true),
('Rajshahi', 'Rajshahi', 'Paba', 120, true),
('Rajshahi', 'Rajshahi', 'Puthia', 120, true),
('Rajshahi', 'Rajshahi', 'Tanore', 120, true),
-- Bogura District
('Rajshahi', 'Bogura', 'Adamdighi', 120, true),
('Rajshahi', 'Bogura', 'Bogura Sadar', 120, true),
('Rajshahi', 'Bogura', 'Dhunat', 120, true),
('Rajshahi', 'Bogura', 'Dhupchanchia', 120, true),
('Rajshahi', 'Bogura', 'Gabtali', 120, true),
('Rajshahi', 'Bogura', 'Kahaloo', 120, true),
('Rajshahi', 'Bogura', 'Nandigram', 120, true),
('Rajshahi', 'Bogura', 'Sariakandi', 120, true),
('Rajshahi', 'Bogura', 'Shajahanpur', 120, true),
('Rajshahi', 'Bogura', 'Sherpur', 120, true),
('Rajshahi', 'Bogura', 'Shibganj', 120, true),
('Rajshahi', 'Bogura', 'Sonatala', 120, true),
-- Joypurhat District
('Rajshahi', 'Joypurhat', 'Akkelpur', 120, true),
('Rajshahi', 'Joypurhat', 'Joypurhat Sadar', 120, true),
('Rajshahi', 'Joypurhat', 'Kalai', 120, true),
('Rajshahi', 'Joypurhat', 'Khetlal', 120, true),
('Rajshahi', 'Joypurhat', 'Panchbibi', 120, true),
-- Naogaon District
('Rajshahi', 'Naogaon', 'Atrai', 120, true),
('Rajshahi', 'Naogaon', 'Badalgachhi', 120, true),
('Rajshahi', 'Naogaon', 'Dhamoirhat', 120, true),
('Rajshahi', 'Naogaon', 'Manda', 120, true),
('Rajshahi', 'Naogaon', 'Mahadebpur', 120, true),
('Rajshahi', 'Naogaon', 'Naogaon Sadar', 120, true),
('Rajshahi', 'Naogaon', 'Niamatpur', 120, true),
('Rajshahi', 'Naogaon', 'Patnitala', 120, true),
('Rajshahi', 'Naogaon', 'Porsha', 120, true),
('Rajshahi', 'Naogaon', 'Raninagar', 120, true),
('Rajshahi', 'Naogaon', 'Sapahar', 120, true),
-- Natore District
('Rajshahi', 'Natore', 'Bagatipara', 120, true),
('Rajshahi', 'Natore', 'Baraigram', 120, true),
('Rajshahi', 'Natore', 'Gurudaspur', 120, true),
('Rajshahi', 'Natore', 'Lalpur', 120, true),
('Rajshahi', 'Natore', 'Natore Sadar', 120, true),
('Rajshahi', 'Natore', 'Singra', 120, true),
('Rajshahi', 'Natore', 'Naldanga', 120, true),
-- Chapainawabganj District
('Rajshahi', 'Chapainawabganj', 'Bholahat', 120, true),
('Rajshahi', 'Chapainawabganj', 'Chapainawabganj Sadar', 120, true),
('Rajshahi', 'Chapainawabganj', 'Gomastapur', 120, true),
('Rajshahi', 'Chapainawabganj', 'Nachole', 120, true),
('Rajshahi', 'Chapainawabganj', 'Shibganj', 120, true),
-- Pabna District
('Rajshahi', 'Pabna', 'Atgharia', 120, true),
('Rajshahi', 'Pabna', 'Bera', 120, true),
('Rajshahi', 'Pabna', 'Bhangura', 120, true),
('Rajshahi', 'Pabna', 'Chatmohar', 120, true),
('Rajshahi', 'Pabna', 'Faridpur', 120, true),
('Rajshahi', 'Pabna', 'Ishwardi', 120, true),
('Rajshahi', 'Pabna', 'Pabna Sadar', 120, true),
('Rajshahi', 'Pabna', 'Santhia', 120, true),
('Rajshahi', 'Pabna', 'Sujanagar', 120, true),
-- Sirajganj District
('Rajshahi', 'Sirajganj', 'Belkuchi', 120, true),
('Rajshahi', 'Sirajganj', 'Chauhali', 120, true),
('Rajshahi', 'Sirajganj', 'Kamarkhanda', 120, true),
('Rajshahi', 'Sirajganj', 'Kazipur', 120, true),
('Rajshahi', 'Sirajganj', 'Raiganj', 120, true),
('Rajshahi', 'Sirajganj', 'Shahjadpur', 120, true),
('Rajshahi', 'Sirajganj', 'Sirajganj Sadar', 120, true),
('Rajshahi', 'Sirajganj', 'Tarash', 120, true),
('Rajshahi', 'Sirajganj', 'Ullapara', 120, true),

-- ============================================================
-- 4. KHULNA DIVISION
-- ============================================================
-- Khulna District
('Khulna', 'Khulna', 'Batiaghata', 120, true),
('Khulna', 'Khulna', 'Dacope', 120, true),
('Khulna', 'Khulna', 'Dighalia', 120, true),
('Khulna', 'Khulna', 'Dumuria', 120, true),
('Khulna', 'Khulna', 'Koyra', 120, true),
('Khulna', 'Khulna', 'Paikgachha', 120, true),
('Khulna', 'Khulna', 'Phultala', 120, true),
('Khulna', 'Khulna', 'Rupsha', 120, true),
('Khulna', 'Khulna', 'Terokhada', 120, true),
-- Jashore District
('Khulna', 'Jashore', 'Abhaynagar', 120, true),
('Khulna', 'Jashore', 'Bagherpara', 120, true),
('Khulna', 'Jashore', 'Chaugachha', 120, true),
('Khulna', 'Jashore', 'Jashore Sadar', 120, true),
('Khulna', 'Jashore', 'Jhikargachha', 120, true),
('Khulna', 'Jashore', 'Keshabpur', 120, true),
('Khulna', 'Jashore', 'Manirampur', 120, true),
('Khulna', 'Jashore', 'Sharsha', 120, true),
-- Satkhira District
('Khulna', 'Satkhira', 'Assasuni', 120, true),
('Khulna', 'Satkhira', 'Debhata', 120, true),
('Khulna', 'Satkhira', 'Kaliganj', 120, true),
('Khulna', 'Satkhira', 'Kalaroa', 120, true),
('Khulna', 'Satkhira', 'Satkhira Sadar', 120, true),
('Khulna', 'Satkhira', 'Shyamnagar', 120, true),
('Khulna', 'Satkhira', 'Tala', 120, true),
-- Bagerhat District
('Khulna', 'Bagerhat', 'Bagerhat Sadar', 120, true),
('Khulna', 'Bagerhat', 'Chitalmari', 120, true),
('Khulna', 'Bagerhat', 'Fakirhat', 120, true),
('Khulna', 'Bagerhat', 'Kachua', 120, true),
('Khulna', 'Bagerhat', 'Mollahat', 120, true),
('Khulna', 'Bagerhat', 'Mongla', 120, true),
('Khulna', 'Bagerhat', 'Morrelganj', 120, true),
('Khulna', 'Bagerhat', 'Rampal', 120, true),
('Khulna', 'Bagerhat', 'Sarankhola', 120, true),
-- Narail District
('Khulna', 'Narail', 'Kalia', 120, true),
('Khulna', 'Narail', 'Lohagara', 120, true),
('Khulna', 'Narail', 'Narail Sadar', 120, true),
-- Jhenaidah District
('Khulna', 'Jhenaidah', 'Harinakunda', 120, true),
('Khulna', 'Jhenaidah', 'Jhenaidah Sadar', 120, true),
('Khulna', 'Jhenaidah', 'Kaliganj', 120, true),
('Khulna', 'Jhenaidah', 'Kotchandpur', 120, true),
('Khulna', 'Jhenaidah', 'Maheshpur', 120, true),
('Khulna', 'Jhenaidah', 'Shailkupa', 120, true),
-- Magura District
('Khulna', 'Magura', 'Magura Sadar', 120, true),
('Khulna', 'Magura', 'Mohammadpur', 120, true),
('Khulna', 'Magura', 'Shalikha', 120, true),
('Khulna', 'Magura', 'Sreepur', 120, true),
-- Kushtia District
('Khulna', 'Kushtia', 'Bheramara', 120, true),
('Khulna', 'Kushtia', 'Daulatpur', 120, true),
('Khulna', 'Kushtia', 'Khoksa', 120, true),
('Khulna', 'Kushtia', 'Kumarkhali', 120, true),
('Khulna', 'Kushtia', 'Kushtia Sadar', 120, true),
('Khulna', 'Kushtia', 'Mirpur', 120, true),
-- Chuadanga District
('Khulna', 'Chuadanga', 'Alamdanga', 120, true),
('Khulna', 'Chuadanga', 'Chuadanga Sadar', 120, true),
('Khulna', 'Chuadanga', 'Damurhuda', 120, true),
('Khulna', 'Chuadanga', 'Jibannagar', 120, true),
-- Meherpur District
('Khulna', 'Meherpur', 'Gangni', 120, true),
('Khulna', 'Meherpur', 'Meherpur Sadar', 120, true),
('Khulna', 'Meherpur', 'Mujibnagar', 120, true),

-- ============================================================
-- 5. BARISHAL DIVISION
-- ============================================================
-- Barishal District
('Barishal', 'Barishal', 'Agailjhara', 120, true),
('Barishal', 'Barishal', 'Babuganj', 120, true),
('Barishal', 'Barishal', 'Bakerganj', 120, true),
('Barishal', 'Barishal', 'Banaripara', 120, true),
('Barishal', 'Barishal', 'Gaurnadi', 120, true),
('Barishal', 'Barishal', 'Hizla', 120, true),
('Barishal', 'Barishal', 'Barishal Sadar', 120, true),
('Barishal', 'Barishal', 'Mehendiganj', 120, true),
('Barishal', 'Barishal', 'Muladi', 120, true),
('Barishal', 'Barishal', 'Wazirpur', 120, true),
-- Bhola District
('Barishal', 'Bhola', 'Bhola Sadar', 120, true),
('Barishal', 'Bhola', 'Burhanuddin', 120, true),
('Barishal', 'Bhola', 'Char Fasson', 120, true),
('Barishal', 'Bhola', 'Daulatkhan', 120, true),
('Barishal', 'Bhola', 'Lalmohan', 120, true),
('Barishal', 'Bhola', 'Manpura', 120, true),
('Barishal', 'Bhola', 'Tazumuddin', 120, true),
-- Patuakhali District
('Barishal', 'Patuakhali', 'Bauphal', 120, true),
('Barishal', 'Patuakhali', 'Dashmina', 120, true),
('Barishal', 'Patuakhali', 'Dumki', 120, true),
('Barishal', 'Patuakhali', 'Galachipa', 120, true),
('Barishal', 'Patuakhali', 'Kalapara', 120, true),
('Barishal', 'Patuakhali', 'Mirzaganj', 120, true),
('Barishal', 'Patuakhali', 'Patuakhali Sadar', 120, true),
('Barishal', 'Patuakhali', 'Rangabali', 120, true),
-- Pirojpur District
('Barishal', 'Pirojpur', 'Bhandaria', 120, true),
('Barishal', 'Pirojpur', 'Kawkhali', 120, true),
('Barishal', 'Pirojpur', 'Mathbaria', 120, true),
('Barishal', 'Pirojpur', 'Nazirpur', 120, true),
('Barishal', 'Pirojpur', 'Nesarabad (Swarupkathi)', 120, true),
('Barishal', 'Pirojpur', 'Pirojpur Sadar', 120, true),
('Barishal', 'Pirojpur', 'Zianagar', 120, true),
-- Jhalokathi District
('Barishal', 'Jhalokathi', 'Jhalokathi Sadar', 120, true),
('Barishal', 'Jhalokathi', 'Kathalia', 120, true),
('Barishal', 'Jhalokathi', 'Nalchity', 120, true),
('Barishal', 'Jhalokathi', 'Rajapur', 120, true),
-- Barguna District
('Barishal', 'Barguna', 'Amtali', 120, true),
('Barishal', 'Barguna', 'Bamna', 120, true),
('Barishal', 'Barguna', 'Barguna Sadar', 120, true),
('Barishal', 'Barguna', 'Betagi', 120, true),
('Barishal', 'Barguna', 'Patharghata', 120, true),
('Barishal', 'Barguna', 'Taltali', 120, true),

-- ============================================================
-- 6. SYLHET DIVISION
-- ============================================================
-- Sylhet District
('Sylhet', 'Sylhet', 'Balaganj', 120, true),
('Sylhet', 'Sylhet', 'Beanibazar', 120, true),
('Sylhet', 'Sylhet', 'Bishwanath', 120, true),
('Sylhet', 'Sylhet', 'Companiganj', 120, true),
('Sylhet', 'Sylhet', 'Dakshin Surma', 120, true),
('Sylhet', 'Sylhet', 'Fenchuganj', 120, true),
('Sylhet', 'Sylhet', 'Golapganj', 120, true),
('Sylhet', 'Sylhet', 'Gowainghat', 120, true),
('Sylhet', 'Sylhet', 'Jaintiapur', 120, true),
('Sylhet', 'Sylhet', 'Kanaighat', 120, true),
('Sylhet', 'Sylhet', 'Sylhet Sadar', 120, true),
('Sylhet', 'Sylhet', 'Zakiganj', 120, true),
-- Moulvibazar District
('Sylhet', 'Moulvibazar', 'Barlekha', 120, true),
('Sylhet', 'Moulvibazar', 'Juri', 120, true),
('Sylhet', 'Moulvibazar', 'Kamalganj', 120, true),
('Sylhet', 'Moulvibazar', 'Kulaura', 120, true),
('Sylhet', 'Moulvibazar', 'Moulvibazar Sadar', 120, true),
('Sylhet', 'Moulvibazar', 'Rajnagar', 120, true),
('Sylhet', 'Moulvibazar', 'Sreemangal', 120, true),
-- Habiganj District
('Sylhet', 'Habiganj', 'Ajmiriganj', 120, true),
('Sylhet', 'Habiganj', 'Bahubal', 120, true),
('Sylhet', 'Habiganj', 'Baniachong', 120, true),
('Sylhet', 'Habiganj', 'Chunarughat', 120, true),
('Sylhet', 'Habiganj', 'Habiganj Sadar', 120, true),
('Sylhet', 'Habiganj', 'Lakhai', 120, true),
('Sylhet', 'Habiganj', 'Madhabpur', 120, true),
('Sylhet', 'Habiganj', 'Nabiganj', 120, true),
-- Sunamganj District
('Sylhet', 'Sunamganj', 'Bishwambarpur', 120, true),
('Sylhet', 'Sunamganj', 'Chhatak', 120, true),
('Sylhet', 'Sunamganj', 'Dakshin Sunamganj', 120, true),
('Sylhet', 'Sunamganj', 'Derai', 120, true),
('Sylhet', 'Sunamganj', 'Dharampasha', 120, true),
('Sylhet', 'Sunamganj', 'Dowarabazar', 120, true),
('Sylhet', 'Sunamganj', 'Jagannathpur', 120, true),
('Sylhet', 'Sunamganj', 'Jamalganj', 120, true),
('Sylhet', 'Sunamganj', 'Sunamganj Sadar', 120, true),
('Sylhet', 'Sunamganj', 'Shalla', 120, true),
('Sylhet', 'Sunamganj', 'Tahirpur', 120, true),

-- ============================================================
-- 7. RANGPUR DIVISION
-- ============================================================
-- Rangpur District
('Rangpur', 'Rangpur', 'Badarganj', 120, true),
('Rangpur', 'Rangpur', 'Gangachara', 120, true),
('Rangpur', 'Rangpur', 'Kaunia', 120, true),
('Rangpur', 'Rangpur', 'Rangpur Sadar', 120, true),
('Rangpur', 'Rangpur', 'Mithapukur', 120, true),
('Rangpur', 'Rangpur', 'Pirgachha', 120, true),
('Rangpur', 'Rangpur', 'Pirganj', 120, true),
('Rangpur', 'Rangpur', 'Taraganj', 120, true),
-- Dinajpur District
('Rangpur', 'Dinajpur', 'Birampur', 120, true),
('Rangpur', 'Dinajpur', 'Birganj', 120, true),
('Rangpur', 'Dinajpur', 'Biral', 120, true),
('Rangpur', 'Dinajpur', 'Bochaganj', 120, true),
('Rangpur', 'Dinajpur', 'Chirirbandar', 120, true),
('Rangpur', 'Dinajpur', 'Dinajpur Sadar', 120, true),
('Rangpur', 'Dinajpur', 'Ghoraghat', 120, true),
('Rangpur', 'Dinajpur', 'Hakimpur', 120, true),
('Rangpur', 'Dinajpur', 'Kaharole', 120, true),
('Rangpur', 'Dinajpur', 'Khansama', 120, true),
('Rangpur', 'Dinajpur', 'Nawabganj', 120, true),
('Rangpur', 'Dinajpur', 'Parbatipur', 120, true),
-- Thakurgaon District
('Rangpur', 'Thakurgaon', 'Baliadangi', 120, true),
('Rangpur', 'Thakurgaon', 'Haripur', 120, true),
('Rangpur', 'Thakurgaon', 'Pirganj', 120, true),
('Rangpur', 'Thakurgaon', 'Ranishankail', 120, true),
('Rangpur', 'Thakurgaon', 'Thakurgaon Sadar', 120, true),
-- Panchagarh District
('Rangpur', 'Panchagarh', 'Atwari', 120, true),
('Rangpur', 'Panchagarh', 'Boda', 120, true),
('Rangpur', 'Panchagarh', 'Debiganj', 120, true),
('Rangpur', 'Panchagarh', 'Panchagarh Sadar', 120, true),
('Rangpur', 'Panchagarh', 'Tetulia', 120, true),
-- Nilphamari District
('Rangpur', 'Nilphamari', 'Dimla', 120, true),
('Rangpur', 'Nilphamari', 'Domar', 120, true),
('Rangpur', 'Nilphamari', 'Jaldhaka', 120, true),
('Rangpur', 'Nilphamari', 'Kishoreganj', 120, true),
('Rangpur', 'Nilphamari', 'Nilphamari Sadar', 120, true),
('Rangpur', 'Nilphamari', 'Saidpur', 120, true),
-- Lalmonirhat District
('Rangpur', 'Lalmonirhat', 'Aditmari', 120, true),
('Rangpur', 'Lalmonirhat', 'Hatibandha', 120, true),
('Rangpur', 'Lalmonirhat', 'Kaliganj', 120, true),
('Rangpur', 'Lalmonirhat', 'Lalmonirhat Sadar', 120, true),
('Rangpur', 'Lalmonirhat', 'Patgram', 120, true),
-- Kurigram District
('Rangpur', 'Kurigram', 'Bhurungamari', 120, true),
('Rangpur', 'Kurigram', 'Char Rajibpur', 120, true),
('Rangpur', 'Kurigram', 'Chilmari', 120, true),
('Rangpur', 'Kurigram', 'Fulbari', 120, true),
('Rangpur', 'Kurigram', 'Kurigram Sadar', 120, true),
('Rangpur', 'Kurigram', 'Nageshwari', 120, true),
('Rangpur', 'Kurigram', 'Rajarhat', 120, true),
('Rangpur', 'Kurigram', 'Raumari', 120, true),
('Rangpur', 'Kurigram', 'Ulipur', 120, true),
-- Gaibandha District
('Rangpur', 'Gaibandha', 'Fulchhari', 120, true),
('Rangpur', 'Gaibandha', 'Gaibandha Sadar', 120, true),
('Rangpur', 'Gaibandha', 'Gobindaganj', 120, true),
('Rangpur', 'Gaibandha', 'Palashbari', 120, true),
('Rangpur', 'Gaibandha', 'Sadullapur', 120, true),
('Rangpur', 'Gaibandha', 'Sundarganj', 120, true),

-- ============================================================
-- 8. MYMENSINGH DIVISION
-- ============================================================
-- Mymensingh District
('Mymensingh', 'Mymensingh', 'Bhaluka', 120, true),
('Mymensingh', 'Mymensingh', 'Dhobaura', 120, true),
('Mymensingh', 'Mymensingh', 'Fulbaria', 120, true),
('Mymensingh', 'Mymensingh', 'Gaffargaon', 120, true),
('Mymensingh', 'Mymensingh', 'Gauripur', 120, true),
('Mymensingh', 'Mymensingh', 'Haluaghat', 120, true),
('Mymensingh', 'Mymensingh', 'Ishwarganj', 120, true),
('Mymensingh', 'Mymensingh', 'Mymensingh Sadar', 120, true),
('Mymensingh', 'Mymensingh', 'Muktagachha', 120, true),
('Mymensingh', 'Mymensingh', 'Nandail', 120, true),
('Mymensingh', 'Mymensingh', 'Phulpur', 120, true),
('Mymensingh', 'Mymensingh', 'Trishal', 120, true),
-- Jamalpur District
('Mymensingh', 'Jamalpur', 'Bakshiganj', 120, true),
('Mymensingh', 'Jamalpur', 'Dewanganj', 120, true),
('Mymensingh', 'Jamalpur', 'Islampur', 120, true),
('Mymensingh', 'Jamalpur', 'Jamalpur Sadar', 120, true),
('Mymensingh', 'Jamalpur', 'Madarganj', 120, true),
('Mymensingh', 'Jamalpur', 'Melandaha', 120, true),
('Mymensingh', 'Jamalpur', 'Sarishabari', 120, true),
-- Netrokona District
('Mymensingh', 'Netrokona', 'Atpara', 120, true),
('Mymensingh', 'Netrokona', 'Barhatta', 120, true),
('Mymensingh', 'Netrokona', 'Durgapur', 120, true),
('Mymensingh', 'Netrokona', 'Kalmakanda', 120, true),
('Mymensingh', 'Netrokona', 'Kendua', 120, true),
('Mymensingh', 'Netrokona', 'Khaliajuri', 120, true),
('Mymensingh', 'Netrokona', 'Madan', 120, true),
('Mymensingh', 'Netrokona', 'Mohanganj', 120, true),
('Mymensingh', 'Netrokona', 'Netrokona Sadar', 120, true),
('Mymensingh', 'Netrokona', 'Purbadhala', 120, true),
-- Sherpur District
('Mymensingh', 'Sherpur', 'Jhenaigati', 120, true),
('Mymensingh', 'Sherpur', 'Nakla', 120, true),
('Mymensingh', 'Sherpur', 'Nalitabari', 120, true),
('Mymensingh', 'Sherpur', 'Sherpur Sadar', 120, true),
('Mymensingh', 'Sherpur', 'Sreebardi', 120, true);
