INSERT INTO public.delivery_zones (division, zilla, upazilla, area, charge, is_active) VALUES
('Dhaka','Dhaka','Dhaka City','Gulshan',40,true),
('Dhaka','Dhaka','Dhaka City','Banani',40,true),
('Dhaka','Dhaka','Dhaka City','Baridhara',40,true),
('Dhaka','Dhaka','Dhaka City','Bashundhara',40,true),
('Dhaka','Dhaka','Dhaka City','Badda',40,true),
('Dhaka','Dhaka','Dhaka City','Rampura',40,true),
('Dhaka','Dhaka','Dhaka City','Aftabnagar',40,true),
('Dhaka','Dhaka','Dhaka City','Niketon',40,true),
('Dhaka','Dhaka','Dhaka City','Mohakhali',40,true),
('Dhaka','Dhaka','Dhaka City','Tejgaon',40,true),
('Dhaka','Dhaka','Dhaka City','Tejgaon Industrial Area',40,true),
('Dhaka','Dhaka','Dhaka City','Kawran Bazar',40,true),
('Dhaka','Dhaka','Dhaka City','Shahbagh',40,true),
('Dhaka','Dhaka','Dhaka City','Ramna',40,true),
('Dhaka','Dhaka','Dhaka City','Motijheel',40,true),
('Dhaka','Dhaka','Dhaka City','Dilkusha',40,true),
('Dhaka','Dhaka','Dhaka City','Paltan',40,true),
('Dhaka','Dhaka','Dhaka City','Farmgate',40,true),
('Dhaka','Dhaka','Dhaka City','Green Road',40,true),
('Dhaka','Dhaka','Dhaka City','Elephant Road',40,true),
('Dhaka','Dhaka','Dhaka City','Hatirpool',40,true),
('Dhaka','Dhaka','Dhaka City','Dhanmondi',40,true),
('Dhaka','Dhaka','Dhaka City','Mohammadpur',40,true),
('Dhaka','Dhaka','Dhaka City','Adabor',40,true),
('Dhaka','Dhaka','Dhaka City','Shyamoli',40,true),
('Dhaka','Dhaka','Dhaka City','Kallyanpur',40,true),
('Dhaka','Dhaka','Dhaka City','Mirpur Section 1',40,true),
('Dhaka','Dhaka','Dhaka City','Mirpur Section 2',40,true),
('Dhaka','Dhaka','Dhaka City','Mirpur Section 6',40,true),
('Dhaka','Dhaka','Dhaka City','Mirpur Section 10',40,true),
('Dhaka','Dhaka','Dhaka City','Mirpur Section 11',40,true),
('Dhaka','Dhaka','Dhaka City','Mirpur Section 12',40,true),
('Dhaka','Dhaka','Dhaka City','Mirpur Section 13',40,true),
('Dhaka','Dhaka','Dhaka City','Pallabi',40,true),
('Dhaka','Dhaka','Dhaka City','Kazipara',40,true),
('Dhaka','Dhaka','Dhaka City','Shewrapara',40,true),
('Dhaka','Dhaka','Dhaka City','Agargaon',40,true),
('Dhaka','Dhaka','Dhaka City','Sher-e-Bangla Nagar',40,true),
('Dhaka','Dhaka','Dhaka City','Uttara Sector 1',40,true),
('Dhaka','Dhaka','Dhaka City','Uttara Sector 2',40,true),
('Dhaka','Dhaka','Dhaka City','Uttara Sector 3',40,true),
('Dhaka','Dhaka','Dhaka City','Uttara Sector 4',40,true),
('Dhaka','Dhaka','Dhaka City','Uttara Sector 5',40,true),
('Dhaka','Dhaka','Dhaka City','Uttara Sector 6',40,true),
('Dhaka','Dhaka','Dhaka City','Uttara Sector 7',40,true),
('Dhaka','Dhaka','Dhaka City','Uttara Sector 8',40,true),
('Dhaka','Dhaka','Dhaka City','Uttara Sector 9',40,true),
('Dhaka','Dhaka','Dhaka City','Uttara Sector 10',40,true),
('Dhaka','Dhaka','Dhaka City','Uttara Sector 11',40,true),
('Dhaka','Dhaka','Dhaka City','Uttara Sector 12',40,true),
('Dhaka','Dhaka','Dhaka City','Uttara Sector 13',40,true),
('Dhaka','Dhaka','Dhaka City','Uttara Sector 14',40,true),
('Dhaka','Dhaka','Dhaka City','Abdullahpur',40,true),
('Dhaka','Dhaka','Dhaka City','Tongi',40,true),
('Dhaka','Dhaka','Dhaka City','Airport Area',40,true),
('Dhaka','Dhaka','Dhaka City','Khilkhet',40,true),
('Dhaka','Dhaka','Dhaka City','Nikunja',40,true),
('Dhaka','Dhaka','Dhaka City','Kuril',40,true),
('Dhaka','Dhaka','Dhaka City','Vatara',40,true),
('Dhaka','Dhaka','Dhaka City','Basabo',40,true),
('Dhaka','Dhaka','Dhaka City','Sabujbagh',40,true),
('Dhaka','Dhaka','Dhaka City','Khilgaon',40,true),
('Dhaka','Dhaka','Dhaka City','Malibagh',40,true),
('Dhaka','Dhaka','Dhaka City','Moghbazar',40,true),
('Dhaka','Dhaka','Dhaka City','Shantinagar',40,true),
('Dhaka','Dhaka','Dhaka City','Kakrail',40,true),
('Dhaka','Dhaka','Dhaka City','Segunbagicha',40,true),
('Dhaka','Dhaka','Dhaka City','Bijoynagar',40,true),
('Dhaka','Dhaka','Dhaka City','Arambagh',40,true),
('Dhaka','Dhaka','Dhaka City','Fakirapool',40,true),
('Dhaka','Dhaka','Dhaka City','Gopibagh',40,true),
('Dhaka','Dhaka','Dhaka City','Jatrabari',40,true),
('Dhaka','Dhaka','Dhaka City','Demra',40,true),
('Dhaka','Dhaka','Dhaka City','Shyampur',40,true),
('Dhaka','Dhaka','Dhaka City','Dholai Khal',40,true),
('Dhaka','Dhaka','Dhaka City','Sutrapur',40,true),
('Dhaka','Dhaka','Dhaka City','Wari',40,true),
('Dhaka','Dhaka','Dhaka City','Gandaria',40,true),
('Dhaka','Dhaka','Dhaka City','Bangshal',40,true),
('Dhaka','Dhaka','Dhaka City','Chawkbazar',40,true),
('Dhaka','Dhaka','Dhaka City','Lalbagh',40,true),
('Dhaka','Dhaka','Dhaka City','Hazaribagh',40,true),
('Dhaka','Dhaka','Dhaka City','Kamrangirchar',40,true),
('Dhaka','Dhaka','Dhaka City','Keraniganj',40,true),
('Dhaka','Dhaka','Dhaka City','Postogola',40,true),
('Dhaka','Dhaka','Dhaka City','Swarighat',40,true),
('Dhaka','Dhaka','Dhaka City','Sadarghat',40,true),
('Dhaka','Dhaka','Dhaka City','Islampur',40,true),
('Dhaka','Dhaka','Dhaka City','Nawabpur',40,true),
('Dhaka','Dhaka','Dhaka City','English Road',40,true),
('Dhaka','Dhaka','Dhaka City','Azimpur',40,true),
('Dhaka','Dhaka','Dhaka City','New Market',40,true),
('Dhaka','Dhaka','Dhaka City','Nilkhet',40,true),
('Dhaka','Dhaka','Dhaka City','Science Lab',40,true),
('Dhaka','Dhaka','Dhaka City','Kalabagan',40,true),
('Dhaka','Dhaka','Dhaka City','Panthapath',40,true),
('Dhaka','Dhaka','Dhaka City','Bosila',40,true),
('Dhaka','Dhaka','Dhaka City','Rayer Bazar',40,true),
('Dhaka','Dhaka','Dhaka City','Jigatola',40,true),
('Dhaka','Dhaka','Dhaka City','Shahjahanpur',40,true),
('Dhaka','Dhaka','Dhaka City','Motijheel Colony',40,true),
('Dhaka','Dhaka','Dhaka City','Mugda',40,true),
('Dhaka','Dhaka','Dhaka City','Manda',40,true),
('Dhaka','Dhaka','Dhaka City','Meradia',40,true),
('Dhaka','Dhaka','Dhaka City','Trimohoni',40,true),
('Dhaka','Dhaka','Dhaka City','Madartek',40,true),
('Dhaka','Dhaka','Dhaka City','Dakkhinkhan',40,true),
('Dhaka','Dhaka','Dhaka City','Uttar Khan',40,true),
('Dhaka','Dhaka','Dhaka City','Dakshinkhan',40,true),
('Dhaka','Dhaka','Dhaka City','Banasree',40,true),
('Dhaka','Dhaka','Dhaka City','Purbachal',40,true),
('Dhaka','Dhaka','Dhaka City','Savar',40,true),
('Dhaka','Dhaka','Dhaka City','Ashulia',40,true),
('Dhaka','Dhaka','Dhaka City','Hemayetpur',40,true),
('Dhaka','Dhaka','Dhaka City','Zirabo',40,true),
('Dhaka','Dhaka','Dhaka City','Gazipur',40,true),
('Dhaka','Dhaka','Dhaka City','Board Bazar',40,true),
('Dhaka','Dhaka','Dhaka City','Pubail',40,true);